#ifndef STATICDYNAMICLOADER_GLOBAL_H
#define STATICDYNAMICLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATICDYNAMICLOADER_LIBRARY)
#  define STATICDYNAMICLOADER_EXPORT Q_DECL_EXPORT
#else
#  define STATICDYNAMICLOADER_EXPORT Q_DECL_IMPORT
#endif

#endif // STATICDYNAMICLOADER_GLOBAL_H
